name: arx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python 3.10.*
  - poetry
  - nodejs  # used by semantic-release
  - shellcheck
  # backend
  - clangdev 14.*
  - clangxx 14.*
  - compiler-rt 14.*
  - compilers
  # it would be nice to replace that by lldb, but
  # the latest version on conda-forge is very old.
  - glib
  - libclang-cpp 14.*
  # - libcxx 14.*
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - lld 14.*
  - llvmdev 14.*
